export enum FilterType {
  Equal = 0,
  NotEqual = 1,
  StartsWith = 2,
  EndsWith = 3,
  GreaterThan = 4,
  LessThan = 5,
  LessThanOrEqual = 6,
  GreaterThanOrEqual = 7,
  Between = 8,
  NotBetween = 9,
  IsNotNull = 10,
  IsNull = 11,
  IsNotNullOrWhiteSpace = 12,
  IsNullOrWhiteSpace = 13,
  IsEmpty = 14,
  IsNotEmpty = 15,
  In = 16,
  NotIn = 17,
  Contains = 18,
  NotContains = 19,
}
